Default timeout value changed so as to fix the OPNSense integration o…
mtreinish/pyopnsense pull request #16
Opened 2023-01-01 17:46 UTC by angvoreeth

Default timeout value changed so as to fix the OPNSense integration of HomeAssistant.

Please see issue #15 for more information.

2023-01-30 05:19 UTC, meichthys approved these changes
This should do it 👍

2023-02-01 17:37 UTC, mtreinish requested changes
Thanks for pushing a PR to fix the issue. But, I don't think this is the best way to go about fixing this though. That specific timeout is supposed to just be a default and if you're having issues with API response time that will be very dependent on your local environment (network reliability, opnsense performance, hardware speed, etc) and while 20 seconds fixes it for one environment it might not be enough (or far too long) for others.

My original intent with that global was to treat that as a default value, but to allow users to override it in the `OPNClient` class, by adding a `timeout=DEFAULT_TIMEOUT` keyword argument to `__init__()`, store it as an instance variable and update the `requests` calls to use the instance variable instead of the global. That way we can enable downstream consumers to set a timeout which works for their environment. (then you can expose that as a config option via home assistant and users can tune the timeout as needed). If you could refactor this PR to take this more flexible approach I think it should be good to go.

2023-02-01 17:45 UTC, angvoreeth commented
Indeed, my PR was a quick fix. 

Your proposal is the way to go as it will be cleaner and more suitability for production (less prone to error due to a timeout). 

I will try to find time to refactor this. The homeassitant integration will probably need a refactor too as I see the timeout parameter as an user option in the interface.

Thanks for you feedback.

2023-06-18 18:44 UTC, mtreinish commented
This has been superseded by #18 so I'm going to close this now. Please feel free to re-open if I'm missing something or there is more to discuss here.

2023-06-18 18:44 UTC, closed without merging